# Uncomment the next line to define a global platform for your project
source 'https://git.coding.net/CocoaPods/Specs.git'
#source 'https://github.com/huanglins/VHLNavigation/blob/master/VHLNavigation.podspec'
platform :ios, '9.0'

target 'quysAdvice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'Masonry'
 pod 'YTKNetwork'
 pod 'YYModel'
 pod 'SDWebImage'
 pod 'Reachability'
# pod 'VHLNavigation'

 
  target 'quysDevDemo' do
    pod 'Masonry'

  end

end
